site_name: 'Dave McNally'
description: 'Carp catching, coffee drinking, game playing, MMA loving designer and developer.'
markdown: redcarpet
redcarpet:
    extensions: ['autolink', 'lax_spacing', 'no_intra_emphasis']
permalink: /:title
exclude: [node_modules, scss, Gruntfile.js, LICENSE, package.json, README.md, js, Gemfile, Gemfile.lock, vendor, CNAME]
url: 'http://davemcnally.me'
name: 'Dave McNally'
paginate: 10